server:
  port: 9090

spring:
  application:
    name: ProjetoEventos
  profiles:
    active: dev
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    changeLog: liquibase/master.xml
  properties:
    hibernate:
      jdbc:
        lob:
          lob:
            nonContextualCreation: true
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate.hbm2ddl.auto: create